---
# Source: Chowkidar/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: chowkidar
    group: com.stakater.platform
    provider: stakater
    version: 0.0.18
    chart: "Chowkidar-0.0.18"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: chowkidar
data:
  config.yaml: |-
    controllers:
    - type: pods
      watchcriterion:
        operator: and
        identifiers:
        - resourceExists
        - healthCheckExists
      actions:
      - name: slack
        params:
          channel: channel-name
          token: your-token
